name: "Build iOS App"

on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master, develop ]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: '3.27.1'
          cache: true

      - name: Install CocoaPods
        run: |
          sudo gem install cocoapods
          pod --version

      - name: Verify Xcode installation
        run: |
          xcode-select -p
          xcrun --show-sdk-version

      - name: Flutter doctor
        run: flutter doctor -v

      - name: Install dependencies
        run: |
          flutter pub get
          flutter pub run build_runner build --delete-conflicting-outputs

      - name: Create env file (if missing)
        run: |
          mkdir -p env
          if [ ! -f env/dev.json ]; then
            echo '{}' > env/dev.json
          fi

      - name: Build iOS (no codesign)
        run: |
          flutter build ios \
            --release \
            --no-codesign \
            --flavor dev \
            --dart-define-from-file env/dev.json \
            -t lib/main.dart \
            --verbose

      - name: Create IPA
        run: |
          cd build/ios/iphoneos
          mkdir Payload
          cp -r Runner.app Payload/
          zip -r ../../../boorusama-dev.ipa Payload/

      - name: Upload IPA Artifact
        uses: actions/upload-artifact@v4
        with:
          name: boorusama-ios-dev
          path: boorusama-dev.ipa
          retention-days: 30

      - name: Upload build logs on failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: build-logs
          path: |
            flutter_build.log
            ios/build/
          retention-days: 7
