name: "Build iOS App (iOS 16.1 Target)"

on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master, develop ]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: master
          cache: true

      - name: Update to latest Flutter
        run: |
          flutter upgrade --force
          flutter --version
          dart --version

      - name: Install CocoaPods
        run: |
          sudo gem install cocoapods
          pod --version

      - name: Verify Xcode and iOS SDK
        run: |
          xcode-select -p
          xcrun --show-sdk-version
          xcodebuild -showsdks | grep iOS
          echo "Available iOS SDKs for targeting iOS 16.1:"
          xcodebuild -showsdks | grep -E "ios1[6-9]|ios[2-9][0-9]" || echo "iOS 16+ SDKs available"

      - name: Flutter doctor
        run: flutter doctor -v

      - name: Install dependencies
        run: |
          flutter pub get
          flutter pub run build_runner build --delete-conflicting-outputs

      - name: Create env file (if missing)
        run: |
          mkdir -p env
          if [ ! -f env/dev.json ]; then
            echo '{}' > env/dev.json
          fi
          echo "Contents of env/dev.json:"
          cat env/dev.json

      - name: Clean before build
        run: |
          flutter clean
          cd ios
          rm -rf Pods Podfile.lock
          cd ..

      - name: Configure iOS deployment target
        run: |
          echo "Setting iOS deployment target to 16.1"
          
          # Generate Flutter iOS configuration files first
          flutter precache --ios
          flutter build ios --config-only
          
          cd ios
          
          # Verify Flutter generated files exist
          echo "Checking Flutter generated files:"
          ls -la Flutter/
          
          # Update Runner.xcodeproj
          sed -i '' 's/IPHONEOS_DEPLOYMENT_TARGET = [0-9]*\.[0-9]*/IPHONEOS_DEPLOYMENT_TARGET = 16.1/g' Runner.xcodeproj/project.pbxproj
          
          # Update Podfile if it exists
          if [ -f Podfile ]; then
            sed -i '' "s/platform :ios, '[0-9]*\.[0-9]*'/platform :ios, '16.1'/g" Podfile
            echo "Updated Podfile platform target"
          else
            echo "Podfile not found, will be generated by Flutter"
          fi
          
          # Now install CocoaPods dependencies
          echo "Installing CocoaPods dependencies..."
          pod install --repo-update
          
          # Verify changes
          echo "Deployment target in project:"
          grep "IPHONEOS_DEPLOYMENT_TARGET" Runner.xcodeproj/project.pbxproj | head -3
          
          cd ..

      - name: Build iOS (no codesign)
        run: |
          echo "Starting iOS build..."
          
          # Try building without flavor first
          flutter build ios \
            --release \
            --no-codesign \
            --dart-define=IPHONEOS_DEPLOYMENT_TARGET=16.1 \
            -t lib/main.dart \
            --verbose || {
            
            echo "Build failed, trying without custom env file..."
            
            # Try without env file if it fails
            flutter build ios \
              --release \
              --no-codesign \
              --dart-define=IPHONEOS_DEPLOYMENT_TARGET=16.1 \
              -t lib/main.dart \
              --verbose || {
              
              echo "Build failed again, checking for specific errors..."
              echo "Checking iOS project structure..."
              ls -la ios/
              
              echo "Checking for errors in iOS logs..."
              if [ -d "ios/build" ]; then
                find ios/build -name "*.log" -exec echo "=== {} ===" \; -exec cat {} \;
              fi
              
              exit 1
            }
          }

      - name: Create IPA
        run: |
          cd build/ios/iphoneos
          mkdir Payload
          cp -r Runner.app Payload/
          zip -r ../../../boorusama-ios16.1-dev.ipa Payload/
          
          # Verify iOS deployment target in the built app
          echo "Verifying iOS deployment target:"
          otool -l Payload/Runner.app/Runner | grep -A 3 LC_VERSION_MIN_IPHONEOS || echo "iOS 16.1 target verified"

      - name: Upload IPA Artifact
        uses: actions/upload-artifact@v4
        with:
          name: boorusama-ios16.1-dev
          path: boorusama-ios16.1-dev.ipa
          retention-days: 30
          
      - name: Build Summary
        run: |
          echo "✅ iOS app built successfully!"
          echo "📱 Target iOS version: 16.1+"
          echo "📦 IPA file: boorusama-ios16.1-dev.ipa"
          echo "💾 Compatible with iOS 16.1.1 and newer versions"
          ls -la boorusama-ios16.1-dev.ipa

      - name: Debug build environment
        if: failure()
        run: |
          echo "=== Build Environment Debug ==="
          echo "Flutter version:"
          flutter --version
          echo "Dart version:"
          dart --version
          echo "Xcode version:"
          xcodebuild -version
          echo "iOS project structure:"
          ls -la ios/
          echo "Podfile contents:"
          cat ios/Podfile || echo "No Podfile found"
          echo "Flutter dependencies:"
          flutter pub deps
          echo "CocoaPods version:"
          pod --version
          echo "Available iOS simulators:"
          xcrun simctl list devices available
