name: "Build iOS App (Simple)"

on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master, develop ]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: master
          cache: true

      - name: Install dependencies
        run: |
          echo "Installing Flutter dependencies..."
          flutter pub get
          flutter pub run build_runner build --delete-conflicting-outputs

      - name: Create env files
        run: |
          mkdir -p env
          echo '{"BASE_URL": "", "API_KEY": ""}' > env/dev.json
          echo '{"BASE_URL": "", "API_KEY": ""}' > env/prod.json

      - name: Build iOS
        run: |
          echo "Building iOS app with dev flavor..."
          flutter build ios --release --no-codesign --flavor dev

      - name: Create IPA
        run: |
          echo "Creating IPA..."
          cd build/ios/iphoneos
          mkdir Payload
          cp -r Runner.app Payload/
          zip -r ../../../app.ipa Payload/
          cd ../../..
          echo "✅ IPA created: app.ipa ($(du -h app.ipa | cut -f1))"

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ios-app
          path: app.ipa
          retention-days: 30

      - name: Debug on failure
        if: failure()
        run: |
          echo "=== Build failed ==="
          echo "Flutter doctor:"
          flutter doctor
          echo ""
          echo "Flutter version:"
          flutter --version
          echo ""
          echo "iOS directory contents:"
          ls -la ios/ || echo "No ios directory"
          echo ""
          echo "Available schemes:"
          xcodebuild -list -project ios/Runner.xcodeproj 2>/dev/null || echo "Cannot read Xcode project"
